:@echo off

cd /d %~dp1

del /Q ASYNC_FIFO_ADDR_CTRL.o
del /Q ASYNC_FIFO_ADDR_CTRL.vcd

iverilog -o ASYNC_FIFO_ADDR_CTRL.o -s ASYNC_FIFO_ADDR_CTRL_tb ^
-g2012 ../../src/ASYNC_FIFO_ADDR_CTRL/ASYNC_FIFO_ADDR_CTRL_tb.sv ^
../../src/ASYNC_FIFO_ADDR_CTRL/ASYNC_FIFO_ADDR_CTRL.v ^
../../src/AUDIY_Verilog_IP/ARESETN_SYNC/ARESETN_SYNC.v ^
../../src/AUDIY_Verilog_IP/BIN2GRAY/BIN2GRAY.v

vvp ASYNC_FIFO_ADDR_CTRL.o

gtkwave ASYNC_FIFO_ADDR_CTRL.vcd
